export {
  Activity,
  AlertCircle,
  ArrowRight,
  Award,
  BookOpen,
  Briefcase,
  CheckCircle,
  Code2,
  Download,
  ExternalLink,
  FileText,
  FileText as FileTextIcon,
  Filter,
  FolderOpen,
  Globe,
  GraduationCap,
  Heart,
  Languages,
  Layers,
  Loader2,
  Mail,
  Mail as MailIcon,
  MapPin,
  Menu,
  MessageCircle,
  MessageSquare,
  MessageSquare as MessageIcon,
  Package,
  Search,
  Send,
  Star,
  Terminal,
  User,
  User as UserIcon,
  Users,
  X,
} from "lucide-react";

export const iconSizes = {
  xs: "w-3 h-3",
  sm: "w-4 h-4",
  md: "w-5 h-5",
  lg: "w-6 h-6",
  xl: "w-8 h-8",
  "2xl": "w-10 h-10",
} as const;

export const iconColors = {
  primary: "text-orange-500",
  secondary: "text-gray-400",
  success: "text-green-500",
  error: "text-red-500",
  warning: "text-yellow-500",
  info: "text-blue-500",
} as const;
